### ISSUE TITLE
Rechazado.

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/form1-Alba#1]
- [x] Radio checks se eligen todos a la vez
- [ ] Adaptar el fondo gris al tamaño del contenido
![Screenshot 2024-04-10 at 23 00 41](https://github.com/4GeeksAcademy/form1-Alba/assets/144109471/52540de6-a843-4081-b8d5-baf5a2b799d4)

- [x] Pick State input tiene que ser de tipo Select con opciones
- [x] Adaptar diseño de botones 
![Screenshot 2024-04-10 at 23 01 02](https://github.com/4GeeksAcademy/form1-Alba/assets/144109471/ca3f92f8-8708-4971-a2af-d0816adcb93f)

- [x] Resolver el error
![Screenshot 2024-04-10 at 23 04 02](https://github.com/4GeeksAcademy/form1-Alba/assets/144109471/6e61f771-c6e0-4722-b509-bcd94480b9f1)

**Comment by AllbaLu** [comment]
ya corregí todos los errores y aun estás marcando mi proyecto como rechazado, quisiera saber por qué? te escribí por slack
